---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cb-client
  labels:
    app: cb-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cb-client
  template:
    metadata:
      labels:
        app: cb-client
    spec:
      containers:
      - name: cb-client
        image: clvx/cb:latest
        args:
        - "run"
        - "-u"
        - "http://cb-server"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cb-server
  labels:
    app: cb-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cb-server
  template:
    metadata:
      labels:
        app: cb-server
    spec:
      containers:
      - name: cb-server
        image: clvx/cb:latest
        args: 
        - "serve"

---
apiVersion: v1
kind: Service
metadata:
  name: cb-server
  labels:
    app: cb-server
spec:
  selector:
    app: cb-server
  ports:
    - name: cb-server
      port: 80
      targetPort: 3000
      protocol: TCP
